# Generated by Django 4.1 on 2023-05-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airchina", "0002_remove_aircraft_capability_remove_flight_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="capability",
            field=models.IntegerField(default=100),
        ),
    ]
