# Generated by Django 4.1 on 2023-05-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airchina", "0004_aircraft_seats"),
    ]

    operations = [
        migrations.RemoveField(model_name="flight", name="date",),
    ]
