# Generated by Django 4.1 on 2023-05-11 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airchina", "0009_alter_bookings_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 12, 3, 16, 27, 501589)
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airchina.bookings"
            ),
        ),
    ]
