# Generated by Django 4.1 on 2023-05-11 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("tail_number", models.CharField(max_length=20)),
                ("capability", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Airports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=20)),
                ("time_zone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_num", models.CharField(max_length=20)),
                ("num_ticket", models.IntegerField()),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Passengers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("nationality", models.CharField(max_length=20)),
                ("passport_num", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("web_address", models.CharField(max_length=100)),
                ("airline_login_name", models.CharField(max_length=100)),
                ("airline_login_password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PassengersBookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airchina.bookings",
                    ),
                ),
                (
                    "passengers_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airchina.passengers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_num", models.CharField(max_length=20)),
                ("booking", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("date_time", models.DateTimeField()),
                ("stamp", models.CharField(max_length=20)),
                (
                    "payment_provider_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airchina.paymentprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_num", models.CharField(max_length=100)),
                ("departure_time", models.DateTimeField(default=datetime.datetime.now)),
                ("date", models.DateField(auto_now=True)),
                ("arrival_time", models.DateTimeField(default=datetime.datetime.now)),
                ("price", models.IntegerField()),
                ("price_business", models.IntegerField()),
                ("price_first", models.IntegerField()),
                ("capability", models.IntegerField(default=100)),
                (
                    "airline_company_name",
                    models.CharField(default="airchina", max_length=100),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airchina.aircraft",
                    ),
                ),
                (
                    "arrival_airport",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arriving_flights",
                        to="airchina.airports",
                    ),
                ),
                (
                    "departure_airport",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departing_flights",
                        to="airchina.airports",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookings",
            name="flight",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="airchina.flight",
            ),
        ),
    ]
