# Generated by Django 4.1 on 2023-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airchina", "0003_aircraft_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft", name="seats", field=models.IntegerField(default=100),
        ),
    ]
