# Generated by Django 4.1 on 2023-05-11 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airchina", "0007_bookings_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passengersbookings",
            old_name="passengers_id",
            new_name="passengers",
        ),
        migrations.AlterField(
            model_name="bookings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 12, 2, 56, 4, 890622)
            ),
        ),
    ]
