# Generated by Django 4.1 on 2023-05-11 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "airchina",
            "0008_rename_passengers_id_passengersbookings_passengers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 12, 3, 6, 25, 736939)
            ),
        ),
    ]
